language: ruby

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master
    - next

env:
  - ON_TRAVIS_CI=yes

install: 'gem install bundler -v ">= 1.15" && bundle install --retry=10'

script: 'bundle exec rake acceptance'

sudo: false
